version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:20.10.1-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=20.1.1-r0
            pip install gcc7
            pip install docker-compose==1.27.4
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
